### ISSUE TITLE
code snippets troubles

### ISSUE THREAD

**Issue by PepiBobanov** [Catel/Catel.Templates#230]
Greetings.
I am using older Catel 5.x . My code snippets are wrong now.
How to downgrade Catel - code snippets extension.
Best regards

**Comment by GeertvanHorrik** [comment]
You can manually install the old code snippets in your Visual Studio documents folder.

**Comment by PepiBobanov** [comment]
Which one, i am with VS2022, i saw master branch 5y old.  Is it compatible? What is the version number of previous Extension pack?

**Comment by PepiBobanov** [comment]
Done, finally i figured out how to revert back repository to old updates.
