### ISSUE TITLE
Unable to create a new app net framework with vs2019 of catel project template 

### ISSUE THREAD

**Issue by ruslan79k** [Catel/Catel.Templates#76]
The [link](https://marketplace.visualstudio.com/items?itemName=Catel.Catel-ProjectTemplates-WPF-Application) template creates a net core project, but how to create a net framework project?

**Comment by GeertvanHorrik** [comment]
Change the `TargetFramework` at the top to net462 (or whatever you use). If you are looking for a non-modern project SDK version, I can't help you, we really don't want to go back there (I don't see any advantages there over the modern sdk one).
